QuantumNous/new-api

common/model-ratio.go, controller/relay-mj.go, controller/relay.go, model/midjourney.go, router/relay-router.go
MJ
增加simple-change、list接口，
变换和重试操作区别出来，价格与绘图一样
优化图片返回
=> optimize: MJ 部分调整、优化

web/src/components/OtherSetting.js
=> refactor(OtherSetting): change UI, improve interaction

common/image.go, dto/text_request.go, dto/text_response.go, relay/channel/claude/adaptor.go, relay/channel/claude/constants.go, relay/channel/claude/dto.go, relay/channel/claude/relay-claude.go, service/token_counter.go, web/src/pages/Channel/EditChannel.js, web/src/pages/TopUp/index.js
=> feat: support Claude 3

web/src/components/ChannelsTable.js, web/src/index.css
=> fix: layout issues

README.md, common/constants.go, common/model-ratio.go, controller/model.go, relay/channel/lingyiwanwu/constrants.go, relay/channel/openai/adaptor.go, web/src/constants/channel.constants.js, web/src/pages/Channel/EditChannel.js
01.AI 零一万物的relay
数据结构和 one 一样都用的 31号key
=> feat: support 01.AI

web/src/components/PersonalSetting.js, web/src/components/SystemSetting.js, web/src/pages/Setting/index.js
=> fix(global): error in console under dev mode

web/src/helpers/render.js
=> refactor(helpers): renderGroup function

web/src/pages/Setting/index.js
‌‌Reduce the one-time concurrent requests on the settings page.
=> perf(Setting): setting tab navigation

web/src/components/HeaderBar.js, web/src/components/OperationSetting.js, web/src/components/SystemSetting.js, web/src/context/Theme/index.js, web/src/index.js
重构了 dark mode 的相关代码
并修复了在「运营设置」，「系统设置」面板下，dark mode 不生效的问题
=> fix: the dark mode does not work for the `OperationSetting` and `SystemSetting` panels

web/src/components/MjLogsTable.js
=> add-mj-use-time

common/model-ratio.go, common/utils.go, controller/model.go, dto/pricing.go, middleware/auth.go, model/ability.go, model/pricing.go, model/usedata.go, router/api-router.go, web/src/App.js, web/src/components/LoginForm.js, web/src/components/ModelPricing.js, web/src/components/SiderBar.js, web/src/helpers/data.js, web/src/helpers/render.js, web/src/pages/Pricing/index.js
=> feat: add pricing page

common/model-ratio.go, relay/channel/openai/constant.go
=> Support Gpt4o

common/model-ratio.go, relay/channel/ai360/constants.go, relay/channel/baidu/adaptor.go, relay/channel/baidu/constants.go
Improving the default behavior of Baidu, adding new Baidu and 360 models and prices based on official documentation.
=> Add Baidu Default Behavior and Updating Baidu&360 Models & Prices

common/model-ratio.go, relay/channel/openai/adaptor.go, web/src/pages/Channel/EditChannel.js
=> feat: 自定义渠道功能变更

relay/channel/aws/constants.go
Add  AWS claude-3-5-sonnet model
=> add aws claude-3-5-sonnet

controller/channel-test.go
1. 渠道超时为正确禁用渠道
2. 渠道正常是无法正确启用渠道
=> fix: channel timeout auto-ban and auto-enable

controller/channel-test.go, service/channel.go
=> fix: http code is not properly disabled channel

relay/channel/gemini/relay-gemini.go
=> fix: the base64 format image_url for gemini

common/email-outlook-auth.go, common/email.go
fix send email error using outlook smtp
修复outlook发送邮件错误 issue #390
参考：
- https://stackoverflow.com/questions/57783841/how-to-send-email-using-outlooks-smtp-servers
- https://gist.github.com/andelf/5118732
=> fix: send email error when using outlook smtp

.gitignore
ignore npm build dir, may save many time when commit changes
=> feat: ignore npm build dir

README.md, relay/channel/gemini/adaptor.go
Getting GEMINI API Version Using Environment Variables GEMINI_MODEL_API
=> Modify the GEMINI version acquisition logic and add support for more gemini1.5pro/flash interfaces

README.md
GEMINI_MODEL_API->GEMINI_MODEL_MAP
=> 修改readme错误

main.go, model/log.go, model/main.go
Feature: Support Log DB by One Api
=> Feature: Support Log DB

controller/log.go, model/log.go
=> Fix log page

web/package.json, web/pnpm-lock.yaml, web/src/components/LogsTable.js
=> fix log pagination

common/email-outlook-auth.go, common/email.go
issue: #390 
临时解决一下LOGIN方式登录的邮箱
=> fix: 多地区outlook邮箱和ofb邮箱Auth

common/model-ratio.go, relay/channel/cohere/constant.go
ref:https://cohere.com/pricing
=> Feat: 更新Cohere新模型和定价

README.md, common/constants.go, relay/channel/cohere/dto.go, relay/channel/cohere/relay-cohere.go
添加cohere的safety设置参数 
ref https://docs.cohere.com/docs/safety-modes
=> chore: 适配cohere的safety参数

common/model-ratio.go, constant/env.go, relay/channel/claude/relay-claude.go, relay/channel/gemini/constant.go
=> fix: tool use in claude and add gemini mapping

relay/channel/ollama/adaptor.go
ollama related issues
https://github.com/ollama/ollama/issues/7490
=> ollama /api/embeddings is deprecated, use /api/embed.

common/model-ratio.go, relay/channel/openai/constant.go
=> Chore: support gpt-4o-2024-11-20

README.md, common/constants.go, common/model-ratio.go, relay/channel/ai360/constants.go
=> fix: 360智脑接口地址更新

controller/channel.go, model/channel.go, web/src/components/ChannelsTable.js
=> feat: 兼容渠道搜索下标签聚合功能

web/src/components/HeaderBar.js, web/src/components/PageLayout.js, web/src/components/SiderBar.js, web/src/context/Style/index.js, web/src/index.css, web/src/index.js, web/src/pages/Home/index.js, web/src/pages/Redemption/EditRedemption.js
=> feat: 界面美化

web/package.json, web/pnpm-lock.yaml, web/src/App.js, web/src/pages/Playground/Playground.js
- Upgraded @douyinfe/semi-ui from version 2.63.1 to 2.69.1 in package.json.
- Updated pnpm-lock.yaml to reflect new dependency versions and lockfile format.
- Moved Playground component to a new directory structure under pages.
- Enhanced Playground component with new features and improved user experience.
=> feat: Update dependencies and restructure Playground component

web/src/components/HeaderBar.js
- Introduced a new '定价' (Pricing) item in the HeaderBar navigation for better accessibility to pricing information.
- Updated routing to include the new '/pricing' path.
- Adjusted user display in the HeaderBar for mobile responsiveness, hiding the username on smaller screens for a cleaner interface.
=> feat: Add pricing link to HeaderBar component

constant/channel_setting.go, middleware/distributor.go, model/channel.go, relay/channel/openai/relay-openai.go, relay/common/relay_info.go, web/src/pages/Channel/EditChannel.js
=> feat: implement channel settings configuration

web/src/components/PersonalSetting.js
=> fix bindWeChat tips

relay/channel/gemini/relay-gemini.go
=> fix: 修复gemini thinking在stream下会内容丢失

relay/channel/gemini/constant.go
=> chore: 更新遗漏的gemini模型

web/src/pages/Setting/Operation/ModelSettingsVisualEditor.js
=> fix: 修复添加模型切换模式时，初始化空值导致的判断问题

dto/openai_request.go, relay/channel/gemini/dto.go, relay/channel/gemini/relay-gemini.go
=> 支持gemini结构化输出

common/model-ratio.go, dto/openai_request.go, relay/channel/gemini/constant.go, relay/channel/openai/adaptor.go, relay/channel/openai/constant.go
已测试，添加重写system role 允许目前常见系统提示词的角色转换
=> Feat: 适配o1模型

.gitignore, common/str.go, relay/channel/gemini/relay-gemini.go
兼容了不带 name 的 func call message
仿照 Claude 的部分，允许同时返回 content 和 tool_calls，即使这并不太符合 OpenAI 的原始规范
对于多个工具同时调用，gemini 2.0 flash exp 要求同时返回
=> fix: mutil func call in gemini

relay/relay-text.go
在上下文中存入promptTokens,避免重试过程重复计算
=> fix 重试过程多次获取图片

controller/channel.go, model/ability.go, model/cache.go
Fixes #691
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/Calcium-Ion/new-api/pull/692?shareId=42e0c53e-1874-4e42-9819-5cd7bd5683e8).
=> Fix channel model length issue

common/model-ratio.go, relay/channel/deepseek/constants.go
=> feat: 更新模型和模型倍率

controller/channel-billing.go, controller/channel.go, web/src/pages/Channel/EditChannel.js
1. **新增渠道余额类型**: 为SiliconFlow和DeepSeek渠道添加了余额管理功能。
2. **改进模型列表获取方式**: 在添加渠道时，修改了模型列表的获取逻辑，现在可以根据类型来筛选和获取模型列表，提高了操作的灵活性和效率。
3. **修复批量添加渠道问题**: 解决了在批量添加渠道时模型列表获取失败的问题，确保了批量操作的稳定性和准确性。
=> feat: 新增渠道管理与模型列表获取

setting/chat.go
添加 Chat 客户端 [AIaW](https://github.com/NitroRCr/AIaW) 的自动配置链接
=> feat:  添加 AIaW 的聊天链接

relay/common/relay_info.go
docs: https://www.volcengine.com/docs/82379/1298454
=> feat: add 火山引擎 support stream options

relay/channel/gemini/adaptor.go, relay/channel/gemini/constant.go, relay/channel/gemini/dto.go
REST API Reference Documentation: https://github.com/google-gemini/cookbook/blob/719a27d752aac33f39de18a8d3cb42a70874917e/quickstarts/Get_started_imagen_rest.ipynb
Token Billing Reference Documentation: https://github.com/google-gemini/cookbook/blob/719a27d752aac33f39de18a8d3cb42a70874917e/quickstarts/Counting_Tokens.ipynb
=> feat: add Gemini Imagen image generation support

common/model-ratio.go, relay/channel/claude/constants.go, relay/channel/claude/dto.go, relay/channel/claude/relay-claude.go
Add Claude 3.7 Sonnet thinking mode support
=> feat: Add Claude 3.7 Sonnet thinking mode support

controller/channel-test.go, web/src/components/ChannelsTable.js, web/src/components/LogsTable.js
- Implemented dynamic column visibility for ChannelsTable and LogsTable
- Added localStorage persistence for column preferences
- Introduced column selector modal with select all/reset functionality
- Supported role-based default column visibility
- Added column settings button to table interfaces
=> feat: Add column visibility settings for Channels and Logs tables

relay/channel/gemini/adaptor.go, relay/channel/gemini/constant.go, relay/channel/gemini/dto.go, relay/channel/gemini/relay-gemini.go
REST API Reference Documentation: https://ai.google.dev/gemini-api/docs/embeddings?hl=zh-cn
=> feat: gemini Embeddings support

relay/channel/cohere/constant.go
同步Cohere最新的command a模型，速度挺快，无审，智商一如既往堪忧。
效果介于gemini 2.0 flash和ds v3之间
=> Chore: Sync Cohere Latest Model

middleware/distributor.go, model/channel.go, relay/common/relay_info.go, relay/relay-text.go, web/src/i18n/locales/en.json, web/src/pages/Channel/EditChannel.js
新增特性：渠道 - 参数覆盖
实现了这个功能请求：https://github.com/Calcium-Ion/new-api/issues/906
=> feat: Add Parameters Override

web/src/pages/Setting/Operation/SettingsGeneral.js
=> fix: fixed bug where target.id was null when clicking 'x' icon

controller/channel.go
获取Gemini 模型的列表，使用Gemini兼容openai格式#921
https://ai.google.dev/gemini-api/docs/openai?hl=zh-cn#rest
=> Update: Gemini channel fetch_models

common/constants.go, relay/channel/xai/adaptor.go, relay/channel/xai/constants.go, relay/constant/api_type.go, relay/relay_adaptor.go, setting/operation_setting/model-ratio.go, web/src/constants/channel.constants.js
Ref: https://github.com/QuantumNous/new-api/issues/957 https://github.com/QuantumNous/new-api/issues/955
适配xAI的输出格式和token统计，同步模型倍率, 可能需要打磨。
适配reasoning effort
=> feat: add xAI channel

service/convert.go
The system prompt use wrong field "Type"
=> fix: wrong field for Claude (OpenAI Upstream)

common/constants.go, common/email.go, common/utils.go
=> feat: 增加sendcloud邮件服务器的支持

model/channel.go, web/src/components/ChannelsTable.js, web/src/i18n/locales/en.json
Feature implemented: On the Channel Management page, support searching channels by their API address (Base URL). No additional input box is added; the existing keyword input box is reused.
实现特性：渠道管理页面，支持按渠道 API地址（Base URL）搜索渠道。不新增输入框，复用原本的关键字输入框。
=> feat: support searching channels by base url

relay/channel/vertex/adaptor.go
支持Vertex渠道Gemini模型的thinking|nothinking模型支持。
与Gemini渠道共用thinking开关配置。
=> feat: support thinking suffix for vertex gemini channel

web/src/pages/User/EditUser.js
=> fix: EditUser text error

relay/helper/model_mapped.go
在 渠道-编辑-模型重定向 中实现对链式模型重定向的支持：
```
{
"model-1": "model-2",
"model-2": "model-3"
}
```
请求 model-1 模型时，最终将使用链尾的 model-3 模型。
实现了模型重定向循环检测，不会因为循环的模型重定向而无限循环。
**本次 pr 修复了 A->B->C->B 死循环检测失效的问题。**
---
Implement support for chained model redirection in Channels-Edit-Model redirection:
```
{
"model-1": "model-2",
"model-2": "model-3"
}
```
When requesting with model model-1, it will ultimately use the tail model-3 in the chain.
Added cycle detection for model redirection to prevent infinite loops caused by circular model redirections.
**This PR fixed the infinite loop detection issue in the A->B->C->B cycle.**
=> feat: support model mapping chain 【支持链式模型重定向】

controller/channel-billing.go
=> feat: update OpenRouter balance

model/option.go, service/cf_worker.go, setting/system_setting.go, web/src/components/SystemSetting.js
添加选项允许 worker http request
fix https://github.com/QuantumNous/new-api/issues/1041
=> feat: add option to allow worker HTTP image requests

relay/relay-mj.go
修复设置了渠道proxy, Mj图片请求discord服务器没有走proxy的问题
=> fix: proxy settings not applied when request MJ image url

relay/channel/gemini/relay-gemini.go
gemini2.5pro不支持设置thinkingBudget
=> Fix: Gemini2.5pro ThinkingConfig

relay/relay-image.go
=> Fix: The edit interface is not billed (usage-based pricing).

relay/channel/gemini/relay-gemini.go
获取到的内容的MimeType如果不被Gemini支持则直接报错，而不是继续发送到Gemini。
见https://cloud.google.com/vertex-ai/generative-ai/docs/model-reference/gemini?hl=zh-cn#parameters
使用`https://jsonplaceholder.typicode.com/posts`作为链接
用户侧报错为
```
{
"error": {
"message": "请求上游地址失败 (request id: 20250602190005198187729idUCSKGz)",
"type": "new_api_error",
"param": "",
"code": "convert_request_failed"
}
}
```
new api logs可见
```
[SYS] 2025/06/02 - 18:56:14 | error: MIME type 'application/json; charset=utf-8' from URL 'https://jsonplaceholder.typicode.com/posts' is not supported by Gemini. Supported types are: [video/mpegps image/png image/jpeg video/mp4 video/flv application/pdf audio/mp3 audio/wav text/plain video/mpeg video/avi audio/mpeg video/mov video/mpg video/wmv] 
```
=> feat: 增加对Gemini MimeType类型的验证

README.md
在README中添加该徽章可让DeepWiki每周扫描代码并更新一次Wiki
=> Add DeepWiki Badge in README

relay/channel/gemini/relay-gemini.go
=> Fix: 更新2.5 pro的思考预算范围

relay/channel/ali/text.go
=> 🐛 fix(ali): Remove hardcoding of embedding model names.

relay/channel/ali/adaptor.go, relay/channel/ali/constants.go, relay/channel/ali/dto.go, relay/channel/ali/rerank.go
=> feat: ali rerank

controller/channel-billing.go
增加moonshot(kimi)余额查询实现
官方文档: https://platform.moonshot.cn/docs/api/misc#%E6%9F%A5%E8%AF%A2%E4%BD%99%E9%A2%9D
实现效果:
=> feat: add moonshot(kimi) update balance

controller/task_video.go, middleware/kling_adapter.go, relay/channel/task/kling/adaptor.go, router/video-router.go, web/src/components/table/TaskLogsTable.js
支持可灵官方API格式
1. 文生视频: /v1/videos/text2video
2. 图生视频: /v1/videos/image2video
=> feat: add origin kling api

relay/channel/aws/relay-aws.go, relay/channel/claude/relay-claude.go
=> fix: claude header was not set correctly

web/src/components/table/channels/modals/EditChannelModal.jsx
From: https://github.com/QuantumNous/new-api/pull/1683
=> feat: add duplicate key removal function when edit or add new channel
