QuantumNous/new-api

model/cache.go
fix: the Redis problem in the CacheGetUsername function
=> fix: the Redis problem in the CacheGetUsername function

middleware/distributor.go, relay/common/relay_info.go
`UpstreamModelName` not set after code refactoring, causing failures on baidu and other channels.
=> fix: add missing upstreamModelName

web/src/pages/Channel/EditChannel.js
1. [fix: model names must not contain spaces at both ends](https://github.com/Calcium-Ion/new-api/commit/d160736a4957c6e82cd20eb58c02d8b5b83ae2be)
2. [perf: prompt when the name of the custom model input already exists](https://github.com/Calcium-Ion/new-api/commit/92c1ed7f1dfc7e2f31379f8b9e9191de5abf185e)
=> fix: model name not trimmed

middleware/distributor.go, relay/channel/openai/adaptor.go, relay/common/relay_info.go
目前 `openai_organization` （组织ID）设置只在渠道设置中写入/读取，并不会真正使用在 OpenAI API 调用时。
根据官方文档描述，这个值需要通过 `OpenAI-Organization` 头传递。
=> fix: openai_organization not working

controller/misc.go
当前的对于注册邮箱的验证，对于[aaaa+aa@xx.com](mailto:aaaa+aa@xx.com)或者[aaaa.aa@xx.com](mailto:aaaa.aa@xx.com)是可以检验的，但是对于[a.s.h.l.eynu.ej.a3@gmail.com](mailto:a.s.h.l.eynu.ej.a3@gmail.com)这种谷歌的临时邮箱就无法检验，因此进行修改。
应用场景：限制注册用户无休止的薅羊毛
=> 修改了用户注册使用临时邮箱验证的问题

model/ability.go
修复渠道一次性添加很多model并且group多
提示失败 too many SQL variables
=> fix: 修复渠道一次性添加很多model失败

common/model-ratio.go
https://openrouter.ai/docs#models
Model name of openrouter is prefix with company name, e.g. "model": "anthropic/claude-3-opus:beta", therefore, CompletionRatio will not working, which is only work for prefix with claude-xxx
=> Fix: CompletionRatio is not working for openrouter.ai

common/model-ratio.go, relay/channel/lingyiwanwu/constrants.go, relay/channel/perplexity/constants.go
更新Perplexity和01万物模型，并增加相关模型的价格。对于模型价格，从one-api引入了 价格 * 系数 的方式，以便汇率变动时统一修改系数。目前仅对新增模型使用了新方式。经测试，价格会显示为完整的一长串浮点数，略微影响外观，其余正常。
=> Update Perplexity and 01AI models

controller/channel.go, router/api-router.go, web/src/pages/Channel/EditChannel.js
在模型编辑侧边栏添加一个快速同步上游渠道商模型列表的按钮。用于快速操作。
=> 添加同步上游模型列表按钮

controller/channel-test.go
修复由于没有编写测试成功的处理逻辑，导致openaiErr为空产生的空指针错误
```
{"id":"xxxxxxxxxxxxxxxx","object":"chat.completion","created":1719456755,"choices":[{"index":0,"message":{"role":"assistant","content":"Hello"},"finish_reason":"max_tokens"}],"usage":{"prompt_tokens":8,"completion_tokens":1,"total_tokens":9}} 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xda7802]
goroutine 1425 [running]:
one-api/controller.testAllChannels.func1()
/build/controller/channel-test.go:227 +0x3e2
created by one-api/controller.testAllChannels in goroutine 58
/build/controller/channel-test.go:204 +0x1c5
```
=> fix testAllChannels nil pointer panic

relay/channel/aws/relay-aws.go
aws渠道的adaptor.go文件DoRequest函数返回了nil，然后awsStreamHandler函数将其作为resp，调用resp.Body.Close()导致panic
=> fix: 修复aws claude渠道panic的问题

relay/channel/cloudflare/constant.go
cloudflare已经可以白嫖性能相当优秀的Llama 3.1 8b了，上下文更长更聪明，可以替代目前的量化qwen14b和其他一众小模型，赞美赛博佛祖。
=> Support cloudflare llama3.1-8b

model/channel.go
1. 分组搜索经测试兼容， mysql、sqlite、postgresql
2. 搜索时默认排序 priority desc
=> fix: 渠道多分组查询 sqlite 查询兼容

common/model-ratio.go, relay/channel/zhipu_4v/constants.go
添加了更多智谱的模型：
glm-4-plus, glm-4-0520, glm-4-air, glm-4-airx, glm-4-long, glm-4-flash, glm-4v-plus
=> feat: support more zhipu models

common/model-ratio.go
fix wrong model ratio about chatgpt-4o-latest
补全倍率应该是3,修改错误值4。
用户: 卧槽怎么4olatest比0513还贵？
点名批评.jpg
=> chore: 修正chatgpt-4o-latest补全倍率

relay/channel/ollama/dto.go, relay/channel/ollama/relay-ollama.go
Performed a risky operation, converting the two-dimensional array obtained by ollama into a one-dimensional array through loop iteration to achieve openai compatibility.
=> Continue fixing Ollama embedding return issue

constant/env.go, relay/channel/gemini/adaptor.go, relay/channel/gemini/constant.go
- 添加 gemini-exp-1114 到 ModelList
- 更新 GetRequestURL 以支持 gemini-exp-1114 使用 v1beta API
- 保持其他模型的兼容性不变
- 修复了 gemini-exp-1114 模型 404 错误的问题
feat(gemini): add support for gemini-exp-1114 model
- Add gemini-exp-1114 to ModelList in constant.go
- Update GetRequestURL in adaptor.go to use v1beta API version for gemini-exp-1114
- Keep backward compatibility for other models
This change enables the use of the experimental gemini-exp-1114 model by correctly routing its requests to the v1beta API endpoint while maintaining existing functionality for other models.
=> 增加对于gemini-exp-1114模型的支持，映射到v1beta

common/email.go
Azure Communication Service SMTP 使用 Login 协议而不是 Plain 协议登陆.
修改点：
1. ACS **只**支持 LOGIN auth，兼容处理
2. ACS smtp 使用特定的用户名结构，并非通常的邮箱地址，因此 message id 生成需要兼容处理
3. ACS 使用 From 字段来区分实际发信人，修改原先使用 Account 为发信人的逻辑，同时兼容不填 From 的场景
https://learn.microsoft.com/en-us/azure/communication-services/quickstarts/email/send-email-smtp/send-email-smtp
=> feat: support Azure Comm Service SMTP

web/src/components/HeaderBar.js, web/src/components/PageLayout.js, web/src/components/SiderBar.js, web/src/context/Style/index.js
- Updated HeaderBar, PageLayout, and SiderBar components to manage inner padding state based on selected items.
- Replaced `isChatPage` state with `shouldInnerPadding` in Style context for better clarity and functionality.
- Enhanced user experience by dynamically adjusting content padding based on navigation selections.
=> feat: Refactor style management for inner padding in layout components

README.md, web/src/components/HeaderBar.js, web/src/components/LoginForm.js, web/src/components/SiderBar.js, web/src/pages/Home/index.js
主要修改：
1、将聊天改到HeaderBar上面，方便小白直接使用聊天功能。（移动端的界面保持原来的样式。）
2、给HeaderBar上的主页和聊天按钮增加了鼠标悬停效果，增加视觉反馈。（移动端的界面不增加聊天按钮。）
3、使用postMessage向iframe传参theme-mode，实现切换子页面主题的功能
子页面的js示例
```
<script>
// 接收父页面的主题模式
window.addEventListener('message', function(event) {
if (event.data.themeMode) {
var theme = event.data.themeMode;
// 测试是否正确接受到theme-mode的值
// console.log('Received theme mode from parent:', theme);
applyTheme(theme);
}
});
// 定义一个函数来应用主题
function applyTheme(theme) {
var body = document.body;
if (theme === 'dark') {
body.classList.add("dark-mode");
document.getElementById("darkModeToggle").checked = true;
} else {
body.classList.remove("dark-mode");
document.getElementById("darkModeToggle").checked = false;
}
}
</script>
```
=> 修改图标样式和聊天按钮的位置，子页面切换主题

model/cache.go, model/channel.go
开启自动禁用和缓存之后，在缓存更新之前，每一次请求都会触发自动禁用，不断的对数据库进行更新操作，在高并发情况下会对数据库造成巨大压力
=> 修复自动禁用会对数据库进行多次更新的问题

relay/channel/gemini/relay-gemini.go
测试了一番，其他OpenAI的模型都能正常处理反斜杠，但是Gemini好像还会自动再转义一次
这里手动去掉了
=> fix: 转义 Gemini 工具调用中的反斜杠

relay/channel/gemini/relay-gemini.go, service/image.go
这下才把流程跑通了，令人感慨。
和 gpt-4o 的标准代码（以及 deepseek-chat）同一套也能跑
=> fix: Gemini 函数调用的文本转义，以及其他文件类型的 Base64 支持

model/log.go, web/src/components/LogsTable.js
1. 日志查询增加渠道名称显示：对 渠道ID 增加 tooltip，鼠标悬停时显示渠道名称；点击打开日志详情时增加 `渠道ID - 渠道名称` 内容。 #506
2. 修复历史日志数据 `logs.other` 为空时，前端尝试将空字符串作为JSON解析，报错导致显示空白页的问题
=> Feat: 日志查询增加渠道名称显示

Dockerfile, common/utils.go, relay/channel/openai/relay-openai.go
修复whisper STT计费错误的问题，原来的逻辑是和one-api一样，基于字符数量估算，实际应该根据音频时长。
这个问题导致本项目和one-api的whisper transcription计费值比渠道的实际消耗的少很多，影响较大。
=> fix: incorrect whisper audio usage

dto/openai_request.go, relay/channel/aws/dto.go, relay/channel/baidu/dto.go, relay/channel/claude/dto.go, relay/channel/cloudflare/dto.go, relay/channel/gemini/dto.go, relay/channel/ollama/dto.go, relay/channel/palm/dto.go, relay/channel/tencent/relay-tencent.go, relay/channel/vertex/dto.go, relay/channel/xunfei/dto.go, relay/channel/zhipu/dto.go
The issue was caused by the `omitempty` tag in the Go struct, which prevented the `temperature` field from being included in the JSON output when it was set to 0.
=> Fix temperature not being set to 0 due to json omitempty

relay/channel/gemini/constant.go
移除过时、在modelist找不到的模型，默认添加不带版本号的模型(不带版本号自动重定向到最新版本),如需老版本自己加。
=> chore: 同步gemini模型

common/model-ratio.go
更新deepseek-chat价格（涨 价 了！)
由于开源模型，各家自托管的定价不同，因此补全倍率仅官方名称做限制，其他供应商请自行设置补全倍率（默认1）
=> chore: 同步deepseek价格

.env.example
修复示例配置中MySQL的DSN错误问题，mysql driver 无法识别 mysql:// 字段，删除后driver正常识别
=> bugfix: 配置文件 .env.example 示例配置错误

relay/channel/ollama/adaptor.go
his PR fixes authentication for the Ollama channel. Previously, the API key was not being correctly set in the request header. Now, the `Authorization` header is properly set with the `Bearer` token.
=> fix: Fix Ollama channel authentication

dto/openai_request.go
Many backends depend on the `extra_body` field to implement additional features such as [sglang](https://docs.sglang.ai/backend/structured_outputs.html#EBNF), [siliconflow](https://docs.siliconflow.cn/en/userguide/guides/prefix#4-usage-examples) 
This should address https://github.com/Calcium-Ion/new-api/issues/640
=> feat: Pass extra_body in OpenAI request to the backend

dto/openai_request.go, dto/openai_response.go, relay/channel/openai/relay-openai.go
添加了 issue (#793) 中提到的对 OpenRouter 供应商思考字段的支持（即思考字段为 `reasoning` 而非 `reasoning_content` ）
https://github.com/Sh1n3zZ/new-api/commit/b95142bbacbd3d4b3775393a5b0b2f2d12c2684c#diff-695e2ea0345b4003d32ed4cc7d6d8a1bebcff70f6bff10db0d9c2499b7a6f34dR59-R60
https://github.com/Sh1n3zZ/new-api/commit/b95142bbacbd3d4b3775393a5b0b2f2d12c2684c#diff-695e2ea0345b4003d32ed4cc7d6d8a1bebcff70f6bff10db0d9c2499b7a6f34dR78-R82
- 删除了当 `thinking_to_content` 标识启用时的 `reasoning` 和 `reasoning_content` 字段。因为内容都被转换为 `content` 了没有留下空值的必要。可能会导致部分客户端会通过这相关字段判断返回的内容中是否包含思考内容并进行错误的二次解析。修改后发现思考到主内容的过渡阶段还是会出现类似的字段，于是新增了 `hasContent` 标记用于跟踪响应是否包含主内容。
https://github.com/Sh1n3zZ/new-api/commit/894dce7366f98bac58e39da24a3465305ebe7298#diff-695e2ea0345b4003d32ed4cc7d6d8a1bebcff70f6bff10db0d9c2499b7a6f34dR63-R64
- …
=> fix: adapting return format for openrouter think content (#793)

relay/channel/openai/adaptor.go, relay/channel/openai/relay-openai.go
添加了一个思考起始标志以确保在且仅在有思考起始标志的情况下返回思考结束的 label
=> fix: wrong thinking labels appear in non-thinking models (#861)

relay/channel/aws/constants.go, relay/channel/aws/relay-aws.go
Some model can only be used through with cross-region inference, 
When using cross-region inference, your throughput can reach up to double the default quotas in the region that the inference profile is in. 
1. https://docs.aws.amazon.com/bedrock/latest/userguide/cross-region-inference.html
2. https://docs.aws.amazon.com/bedrock/latest/userguide/inference-profiles-support.html
=> feat: support AWS Model CrossRegion

controller/channel-test.go
#933 渠道测试逻辑，修改Gemini模型中的请求报文的maxOutputTokens值为500，避免出现响应报文中无candidates内容
=> fix: gemini test MaxTokens

web/src/components/SystemSetting.js
由于 OIDC 相关配置 key 含有 `.`，原先前端保存配置时会出错:
期望:
```json
{
"oidc.well_known": "https://...."
}
```
实际情况:
```json
{
"oidc": {
"well_known": "https://...."
}
}
````
该 PR 尝试修复这一问题.
=> fix: save OIDC settings

common/constants.go, common/init.go, constant/env.go, web/package.json
主要修改点：
1、把common/instants.go里的从Getenv获取的参数，放到init.go的LoadEnv函数里获取
2、把constant/env.go里的从Getenv获取的参数，放到env.go的InitEnv函数里获取。
上述改动主要是避免.env文件配置参数不起作用的情况
看代码DEBUG参数是在common/constants.go里的DebugEnabled = os.Getenv("DEBUG") == "true"获取
但是common包初始化的时候，.env文件还没有读进来，这时获取不到环境变量
对应的issue：.env文件配置DEBUG=true不起作用 #951
=> .env文件配置DEBUG=true等参数不起作用的fix

relay/channel/dify/relay-dify.go, relay/helper/stream_scanner.go
- 移除了 bufio 的无效使用
- 在 StreamScannerHandler 中增加了初始和最大缓冲区大小的常量设置
- 调整 StreamScannerHandler 中缓冲区大小，避免出现token too long报错
=> fix(relay): 优化数据流处理

relay/relay-image.go
2025.4.9 grok-2-image: quality, size or style are not supported by xAI API at the moment.
I modified the getAndValidImageRequest function in the relay/relay-image.go file. I added a condition to change the size to an empty string if it is set to "empty". This change is to support the grok-2-image model.
Here's an example of usage:
~~~json
{
"model": "grok-2-image",
"prompt": "A cat in a tree",
"response_format": "url",
"size": "empty",
"n": 1
}
~~~
=> fix: update getAndValidImageRequest function in relay/relay-image.go to support grok-2-image model

relay/channel/gemini/relay-gemini.go
If the `json_schema` is generated using OpenAI's Zod helper function `zodResponseFormat`, it will contain `$schema` property, which will cause the request to fail.
```
Error: 400 Invalid JSON payload received. Unknown name "$schema" at 'generation_config.response_schema': Cannot find field. 
```
=> fix: gemini response json schema

relay/helper/stream_scanner.go, relay/relay-text.go
These changes ensures SSE ping packets are sent before receiving a response from the upstream. The previous implementation did not send ping packets until after the upstream response, rendering the feature ineffective.
Fixes #971 
**Before:**
HTTP 524/504/502 error when using CDN service and the upstream didn't respond within 60/100 seconds
**Now:**
Works without issue since the SSE ping option was enabled.
**Screenshot:**
A simulated response with the first chunk of the response received after 180 seconds.
=> fix: ensure SSE ping packets are sent before upstream response

dto/dalle.go
在ImageRequest结构中添加了两个新字段：Background和Moderation，用于支持更多的图像生成配置选项。
=> 添加DALL-E图像生成请求中的Background和Moderation字段

relay/channel/ali/adaptor.go
通义千问中completions接口错误，导致像roo code, cline等vibe coding工具调用阿里coder模型进行补全时错误。
=> fix: ALI completions api path error

web/src/components/ChannelsTable.js
渠道管理界面, '使用ID排序'状态会保存到localStorage, 刷新页面可以记住, 
'开启批量操作'和'标签聚合模式'状态没有保存,刷新页面状态会失效,
使用和'使用ID排序'一样的逻辑保存到localStorage里解决了
=> fix: keep BatchDelete and TagMode enabled status

web/src/pages/Playground/Playground.js
修复playground默认模型不存在时, 取模型列表第一个兜底, 保证对话可用
=> fix: if default model is not exist, set the first one as default

dto/openai_request.go
修复问题： #1092 
请求chat/completion路由时，指定parallel_tool_calls参数时，将会透传该参数到目标大模型
=> feat: chat/completion路由透传parallel_tool_calls参数

web/src/helpers/api.js
=> fix: include group in payload for playground

model/channel_cache.go, setting/ratio_setting/model_ratio.go
- 先检查模型原名，再检查格式化的通配符名称
- 增加了gemini-2.5-flash-lite的通配符模型名以及定价
- 推荐后续使用通配符模型名，避免添加多个后缀的模型
仅配置精确模型名
调用成功
配置通配符模型名
调用-12345成功
=> fix: 修复通配符处理对判断可用渠道的破坏

web/src/components/layout/headerbar/UserArea.jsx
- Added useRef to manage dropdown positioning in UserArea component.
- Wrapped Dropdown in a div with a ref to ensure correct popup container.
Before
https://github.com/user-attachments/assets/f542cd23-0cc5-42b3-a26f-b232e61cc13d
After
https://github.com/user-attachments/assets/df027b3f-c2d7-459f-b4b9-a9a38540a4a7
=> fix(UserArea): Enhance UserArea dropdown positioning with useRef

web/src/components/common/markdown/MarkdownRenderer.jsx, web/src/helpers/api.js, web/src/helpers/utils.jsx
本PR聚焦解决 #1828 反馈的核心问题——**多行代码复制后换行符丢失**，同时处理两处代码质量问题：一是API payload的重复属性，二是Markdown渲染中代码文本获取的逻辑冗余，最终保证复制功能格式准确性与API请求稳定性。
| 文件路径 | 具体修改 | 目的 |
|----------|----------|------|
| `web/src/helpers/utils.jsx` | 1. 复制逻辑的表单控件从 `<input>` 替换为 `<textarea>`<br>2. 新增 `readonly` 属性防止手动编辑，叠加 `fixed` 定位（left/top: -9999px）隐藏元素 | 1. 核心修复：`<textarea>` 原生支持多行文本，解决换行符丢失问题（#1828）<br>2. 避免新增DOM元素影响页面布局流，同时防止用户误操作 |
| `web/src/helpers/api.js` | 1. 移除 `buildApiPayload` 中重复的 `group: inputs.group` 定义<br>2. 参数校验逻辑拆分为 `enabled`（是否启用）、`value`（入参值）、`hasValue`（非undefined/null校验）三个变量 | 1. 修复对象字面量重复键的语法错误，避免运行时潜在异常<br>2. 解耦复杂条件判断，提升逻辑可读性与后续可维护性 |
| `web/src/components/common/markdown/MarkdownRenderer.jsx` | 1. 拆分代码元素查询与文本获取：先存 `codeElement` 引用，再取文本<br>2. 文本获取从 `innerText` 切换为 `textContent` | 1. 避免链式调用的冗余，让代码执行链路更清晰<br>2. …
=> fix: 修复多行代码复制换行丢失问题 & 优化API参数处理#1828

dto/gemini.go, relay/channel/gemini/relay-gemini.go
=> feat: gemini urlContext
